// This file is generated by build.rs, do not modify manually.
// It is generated by extracting errors from the masm files in the `miden-lib/asm` directory.
//
// To add a new error, define a constant in masm of the pattern `const.ERR_<CATEGORY>_...`.
// Try to fit the error into a pre-existing category if possible (e.g. Account, Prologue,
// Non-Fungible-Asset, ...).
//
// The comment directly above the constant will be interpreted as the error message for that error.

// NOTE ASSERTION ERROR
// ================================================================================================

pub const ERR_POOL_ASSET_IS_NOT_IN_PAIR: u32 = 0x00020080;

pub const ERR_SAME_ASSET_IN_AND_OUT: u32 = 0x00020081;

pub const NOTE_ERRORS: [(u32, &str); 2] = [
    (ERR_POOL_ASSET_IS_NOT_IN_PAIR, "Asset is not in pair error"),

    (ERR_SAME_ASSET_IN_AND_OUT, "Asset is not in pair error"),
];
