// This file is generated by build.rs, do not modify manually.
// It is generated by extracting errors from the masm files in the `miden-lib/asm` directory.
//
// To add a new error, define a constant in masm of the pattern `const.ERR_<CATEGORY>_...`.
// Try to fit the error into a pre-existing category if possible (e.g. Account, Prologue,
// Non-Fungible-Asset, ...).
//
// The comment directly above the constant will be interpreted as the error message for that error.

// NOTE ASSERTION ERROR
// ================================================================================================

pub const ERR_P2ID_PRIVATE_TARGET_ACCT_MISMATCH: u32 = 0x00020061;
pub const ERR_P2ID_PRIVATE_WRONG_NUMBER_OF_INPUTS: u32 = 0x00020060;
pub const ERR_P2ID_TARGET_ACCT_MISMATCH: u32 = 0x00020051;
pub const ERR_P2ID_WRONG_NUMBER_OF_INPUTS: u32 = 0x00020050;

pub const NOTE_ERRORS: [(u32, &str); 4] = [
    (ERR_P2ID_PRIVATE_TARGET_ACCT_MISMATCH, "P2IDPrivate's target account address and transaction address do not match"),
    (ERR_P2ID_PRIVATE_WRONG_NUMBER_OF_INPUTS, "P2IDPrivate script expects exactly 4 note input"),
    (ERR_P2ID_TARGET_ACCT_MISMATCH, "P2ID's target account address and transaction address do not match"),
    (ERR_P2ID_WRONG_NUMBER_OF_INPUTS, "P2ID script expects exactly 1 note input"),
];
